Feature czx
D-Robotics/hobot_dnn pull request #10
Opened 2024-09-03 08:40 UTC by zixi01chen

1. 设置线程池堆积的任务上限为1。

2024-09-03 10:52 UTC, zhukao requested changes

2024-09-03 10:52 UTC, zhukao commented on dnn_node_example/src/dnn_example_node.cpp
> +                  static_cast<int>(perf_postprocess.time_ms_duration),
preprocess?

2024-09-03 10:52 UTC, zhukao commented on dnn_node/src/dnn_node_impl.cpp
> +      return 0;
缓存长度设置成1相当于就是同步推理了。应该按照这里todo说的，扩展错误码，如果错误码是线程池满，example就不应该输出错误。

2024-09-04 03:39 UTC, zixi01chen commented on dnn_node_example/src/dnn_example_node.cpp
> +                  static_cast<int>(perf_postprocess.time_ms_duration),
是的，有错误去修改

2024-09-04 03:40 UTC, zixi01chen commented on dnn_node/src/dnn_node_impl.cpp
> +      return 0;
好的

2024-09-04 04:19 UTC, zhukao commented on dnn_node/CHANGELOG.md
> +1. 设置线程池堆积的任务上限为1。
changelog也更新下吧

2024-09-04 06:05 UTC, zixi01chen commented on dnn_node/CHANGELOG.md
> +1. 设置线程池堆积的任务上限为1。
好的

2024-09-04 06:06 UTC, zhukao approved these changes

2024-09-04 06:07 UTC, merged